services:
  business-db:
    ports: !override []

  keycloak-init:
    environment:
      KEYCLOAK_INTERNAL_URL: http://host.docker.internal:8180

  auth-svc:
    environment:
      KEYCLOAK_INTERNAL_URL: http://host.docker.internal:8180
      KEYCLOAK_JWK_SET_URI: http://host.docker.internal:8180/realms/paktay/protocol/openid-connect/certs
      KEYCLOAK_PUBLIC_URL: https://keycloak.rocketsoftwarecore.com
      KEYCLOAK_ISSUER_URI: https://keycloak.rocketsoftwarecore.com/realms/paktay

  business-svc:
    environment:
      KEYCLOAK_JWK_SET_URI: http://host.docker.internal:8180/realms/paktay/protocol/openid-connect/certs
      KEYCLOAK_HEALTH_URL: http://host.docker.internal:8180/realms/paktay
      KEYCLOAK_ISSUER_URI: https://keycloak.rocketsoftwarecore.com/realms/paktay

volumes:
  business-data:
    external: true
    name: packtay_backend_business-data
