spring.application.name=paktay-business-svc
server.port=${SERVER_PORT:8082}
spring.datasource.url=${BUSINESS_DB_URL:jdbc:postgresql://localhost:5433/paktay}
spring.datasource.username=${BUSINESS_DB_USERNAME:paktay}
spring.datasource.password=${BUSINESS_DB_PASSWORD:ChangeThisBusinessDatabasePassword123!}
spring.flyway.locations=classpath:db/migration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/paktay}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/paktay/protocol/openid-connect/certs}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
