spring.application.name=paktay-auth-svc
server.port=${SERVER_PORT:8081}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/paktay}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/paktay/protocol/openid-connect/certs}

paktay.keycloak.internal-url=${KEYCLOAK_INTERNAL_URL:http://localhost:8180}
paktay.keycloak.public-url=${KEYCLOAK_PUBLIC_URL:http://localhost:8180}
paktay.keycloak.realm=${KEYCLOAK_REALM:paktay}
paktay.keycloak.mobile-client-id=${KEYCLOAK_MOBILE_CLIENT_ID:paktay-mobile}
paktay.keycloak.service-client-id=${KEYCLOAK_SERVICE_CLIENT_ID:paktay-auth-service}
paktay.keycloak.service-client-secret=${KEYCLOAK_SERVICE_CLIENT_SECRET:ChangeThisServiceSecret123!}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
